# Generated by Django 4.2.13 on 2025-07-11 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mp3_editor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mp3file',
            name='downloaded_file',
        ),
    ]
