# Generated by Django 4.2.13 on 2025-07-11 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp3_editor', '0002_remove_mp3file_downloaded_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='mp3file',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='mp3_files/'),
        ),
    ]
