# Generated by Django 4.2.13 on 2025-07-12 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp3_zipper', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ZipFile',
        ),
        migrations.RemoveField(
            model_name='mp3zip',
            name='url',
        ),
        migrations.AddField(
            model_name='mp3zip',
            name='urls',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mp3zip',
            name='zip_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
