# Generated by Django 4.2.13 on 2025-07-12 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp3_zipper', '0002_delete_zipfile_remove_mp3zip_url_mp3zip_urls_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mp3zip',
            name='zip_file',
            field=models.FileField(blank=True, null=True, upload_to='zip_files/'),
        ),
    ]
